### ISSUE TITLE
Emoji "picker"

### ISSUE THREAD

**Issue by jugendhacker** [paul-nameless/tg#100]
I though about how cool it would be if one could input Emojis via the double point syntax like Telegram Desktop also has. I also found a python lib that might be helpful for this so you don't have to care to keep the list update: https://github.com/carpedm20/emoji/

Especially this file might be useful: https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes.py but then there needs to be a auto completion build...

**Comment by lightme16** [comment]
Thanks, we also thought about emoji pickier however didn't implement it in the first version, because it seems to be not essential for the app. Maybe we can add this later.
Also, strictly speaking, picking emoji it is a generic capability and it isn't the responsibility of the telegram client. You can have an external tool that helps you to paste emojis into the various application to follow Unix coventions about software modularity. Here is [example](https://www.youtube.com/watch?v=UCEXY46t3OA) of this idea for Linux and dmenu.

**Comment by paul-nameless** [comment]
I think it is really intuitive and useful but indeed to support it as you propose, we will need to implement auto completion which is another big and complex task. And I want to keep tg as simple as possible.

One of the options mentioned @lightme16. There are a lot of command line emoji pickers in terminal.

Another approach is to use vim or emacs with emoji auto-completion (there is plugins for that).

One of the idea that I got, is to have some shortcut when user is typing new msg. It will launch terminal emoji picker and paste stdout (emoji) when finished in the input field. This is easy to implement and still modular which will allow users to use their own emoji picker.

**Comment by jugendhacker** [comment]
Yeah a shortcut for an emoji picker would totally be fine for me

**Comment by matheusfillipe** [comment]
Another option if you are running X server is to use espanso. 

One idea I have for this problem + sending stickers + sending whatever else, would be approach this as vi registers work. Would it be too hard to implement shortcuts for certain messages? Like I copy some dog animated sticker message which I want to use with y and then I trigger assigning with f (favorites?) and then type`dog`. This way when I type `:dog` in some chat that thing that was copied will be sent.

The same thing could be configurable on the config file as a dict of shortcuts and message id's, string for text/emojis or file paths.

We tend to use the same stickers, emojis and whatever for some time and having this re-assignable to custom shortcuts would be pretty useful if those can be permanent. At least I think so.

Does this make any sense for anyone else?

**Comment by paul-nameless** [comment]
Good idea, I'd use it.
The easier solution that just came up to me is to configure this favorites in the config file and then access like f[shortcut].
E.g.
```
{
  "a": "\ (•◡•) /",
  "b": "👍",
}
```

What do you think guys?

**Comment by matheusfillipe** [comment]
That is really great for emojis! I would also love if it can send files (specially sitckers) like that.

**Comment by paul-nameless** [comment]
Closing in favor of using built into OS/terminal (kitty) emoji picker
