### ISSUE TITLE
How to send a message from shell?

### ISSUE THREAD

**Issue by bubakazouba** [paul-nameless/tg#120]
Is there a way I can pipe a message and username into the program straight from bash? So I can use it in scripting/automation?

**Comment by paul-nameless** [comment]
Currently there is no such ability but we thought about it and see why it might be usefull.

Tdlib allows only one instance at a time. It means, that to make it work, we need implement some kind of RPC, which raises some questions about security.

Also, how would you know group/user id to send? It's possible to implement some kind of auto completion or get id beforehand, but overall it's not very comfortable.

**Comment by bubakazouba** [comment]
Oh I wouldn't mind running this one instance at a time, if it takes ~1-2 seconds to complete sending 1 message. I wouldn't want to send another message at the same time.

> Also, how would you know group/user id to send? 

I was planning on retrieving the telegram id beforehand from the normal CLI and hardcode it in my bash script

**Comment by paul-nameless** [comment]
wontfix, but PR is welcome
