### ISSUE TITLE
Autocompletion when sending files and default file manager to pick

### ISSUE THREAD

**Issue by Yodzorah** [paul-nameless/tg#125]
For example, when I send a picture with a name like `~/pics/soeasytomistypedir/pic1.jpg`, I want to be able to auto-complete `soeasytomistypedir`. And when I choose something like `~/tmp/sdfskdjhsdkjfhsdfsdfsdf.stuff` with many files having rubbish names in that dir, I want to use a file manager like `ranger` with preview feature to pick what I need.

**Comment by paul-nameless** [comment]
We wouldn't want to implement auto completion and prefer using something ready and made specially for these.
I thought about ranger, do you know how to use it to make it return file paths?

**Comment by Yodzorah** [comment]
@paul-nameless, I know of two options:

> **--choosefile**=_targetfile_
>     Allows you to pick a file with ranger.  This changes the behavior so that when you open a file, ranger will exit and write the absolute path of that file into _targetfile_.
> 
> **--choosefiles**=_targetfile_
>     Allows you to pick multiple files with ranger.  This changes the behavior so that when you open a file, ranger will exit and write the absolute paths of all selected files into _targetfile_, adding one newline after each filename.

There's also an example of using these [in a vim script](https://github.com/ranger/ranger/blob/master/examples/vim_file_chooser.vim), if that helps.

**Comment by paul-nameless** [comment]
File picker is implemented but auto completion won't be implemented though PR is welcome)
