### ISSUE TITLE
Vim enters Insert mode before the execution of .vimrc

### ISSUE THREAD

**Issue by Yodzorah** [paul-nameless/tg#129]
Not sure if it's related, but do you somehow make Vim enter Insert mode _before_ it executes `.vimrc` when the user creates a new multiline message?

If it's you, I'd ask you to leave it to user to enter Insert mode or to add an option in `~/.mailcap` by himself, because it's not good for everyone. For example, I use NERDTree plugin, which basically creates an additional window for each tab, with file structure of the current directory, allowing me to navigate files of my projects easily from Vim. The problem is that by default when entering Vim the focus is on that NERDTree window, which I fix in `.vimrc` on Vim start. And that NERDTree buffer is not modifiable, so when Vim is run in Insert mode _before_ executing `.vimrc`, I get errors because it tries to enter Insert mode for a non-modifiable buffer of a NERDTree window instead of entering Insert mode for the window of the message buffer.

**Comment by paul-nameless** [comment]
We thought that it is faster to start typing when sending long msgs. The problem with mailcap, is that all txt files will be opened this way. We'll think what to do with it, for now you can set `LONG_MSG_CMD` variable in config to overwrite default cmd.
```
# TODO: use mailcap instead of editor
LONG_MSG_CMD = "vim + -c 'startinsert' {file_path}"
```

**Comment by paul-nameless** [comment]
Added link to readme to config file with variables which can be overridden.
