### ISSUE TITLE
Glitch in Insert mode

### ISSUE THREAD

**Issue by Yodzorah** [paul-nameless/tg#138]
Not sure how to reproduce, but this is what I did:

1. Open `tg`, open `tg`'s official group chat.
2. Press `i`, start typing a message in Russian, pause, but don't send it yet.
3. Wait for the 'blink' (suppose, that's when `tg` updates messages and chats).
4. Right after the 'blink' happens, `tg` looks like this:

![telegram-tg visual glitch](https://user-images.githubusercontent.com/28236673/87415111-bac2e300-c5dd-11ea-9a0f-96d64b17ad1b.png)

5. Easily cured by typing another character into the still focused input field, the whole app comes back to the way it was, everything readable and as it should be.

Maybe it's related to #96?

**Comment by lightme16** [comment]
+1, having the same issue. We need to revisit code and fix it.

**Comment by paul-nameless** [comment]
This bug should be fixed in the latest version, at least I haven't seen it anymore, reopen if it will happen again, please.
