### ISSUE TITLE
Arch: various crashes on first run

### ISSUE THREAD

**Issue by classabbyamp** [paul-nameless/tg#148]
crashes if `.local/share/tg/all.log` is missing

crashes if `PHONE` isn't in the correct format

**Comment by paul-nameless** [comment]
It should create log directory at first run if no configuration file detected
https://github.com/paul-nameless/tg/blob/master/tg/config.py

I guess you've had config file already?

**Comment by classabbyamp** [comment]
ah, I made the config file before the first run

**Comment by lightme16** [comment]
I think we should still create missing log dir if config file already exists to avoid such problems in future.

**Comment by paul-nameless** [comment]
What was the problem with PHONE format?

**Comment by classabbyamp** [comment]
there was no documentation as to how to format it (`+x-xxx-xxx-xxxx` for example), and there was no error handling so the program crashed with a raw traceback that just said the phone number was not in the correct format

**Comment by paul-nameless** [comment]
@classabbyamp were there any errors with missing `~/.cache/tg/` directory? Or only with local/share one?

**Comment by classabbyamp** [comment]
I don't think so
