### ISSUE TITLE
Support for secret chats

### ISSUE THREAD

**Issue by kovidgoyal** [paul-nameless/tg#150]
I realize its on your TODO list, however, I'd like to now if it is likely to be implemented anytime soon. Thanks.

**Comment by kovidgoyal** [comment]
Oh and I am willing to help with implementing it if needed.

**Comment by paul-nameless** [comment]
Hello Kovid,

It's semi working. If somebody initiating secret chat with you, and other clients not active it will appear in your chat list and you can start conversation.
Need to todo:
- add ability to view secret key to verify
- ability to initiate (create) secret chat
- deleting secret chat is working but not closing

This feature is one of the top requested so I think we'll do it in nearest time (couple of weeks I hope)

**Comment by kovidgoyal** [comment]
That's great to hear. if you need help please let me know, I am happy to contribute, as I need this functionality. Also I am the author of the kitty terminal, so if you need assistance with displaying of images inline, I can help there as well. For example, #149 and #137

**Comment by paul-nameless** [comment]
Thanks for the proposition! That would be really cool if you could help with displaying inline images. Cause I am not really imagine how it should be implemented, how scrolling will work, etc. I know that kitty can draw image of any size on any position of the screen, does it mean that we should keep position of msg and when it is scrolled up/down - redraw image?

P.S. I use kitty every day and I think it's the best terminal emulator. Thanks for making it!

**Comment by kovidgoyal** [comment]
if you use normal screen (not alternate screen) then the images scroll automatically when text scrolls. You can see this is action by simply doing kitty +kitten icat some_image and then pressing enter a few times, you will see the image scrolling up with the text.

However, if you use the alternate screen mode, then you are responsible for doing your own scrolling, in this case you must manually move the images as you scroll the content. For an example of that, look at the kitty diff kitten, which does precisely this. https://sw.kovidgoyal.net/kitty/kittens/diff.html

The code for this kitten lives in the kitty reporsitory under kittens/diff
