### ISSUE TITLE
how to not auto download files.

### ISSUE THREAD

**Issue by harimurtie** [paul-nameless/tg#163]
the download thing is confusing for me. i know the 10MB limit,but sometimes less than 1MB picture is not downloaded but 5MB pdf file got downloaded.sometimes sticker is downloaded , sometimes not.  i usually dont auto download anything.  can you made on demand file download?

**Comment by paul-nameless** [comment]
Hello,
You can set `MAX_DOWNLOAD_SIZE = "0MB"` in config file and it will prevent any file from been downloaded.
When you need to download something, press `D`.
Also, fyi, you can copy file path with `y` (yank).
