### ISSUE TITLE
Add a keybinding to download files

### ISSUE THREAD

**Issue by kovidgoyal** [paul-nameless/tg#172]
Something like 'd' which will download the files in the selected messages to a pre specified folder, settable in config.py, defaulting to /tmp

**Comment by paul-nameless** [comment]
There is a keybinding `D` which downloads file and if you press `y` it will copy path to the file.
All files are managed by tdlib and downloaded under `FILES_DIR = os.path.expanduser("~/.cache/tg/")`
Files: `~/.cache/tg/files/`

**Comment by kovidgoyal** [comment]
Right, I want a keybinding that will let me download the file directly
into a directory other than the cache, so I dont have to bother with
copying it out manually. Either the directory can be specified in the
config file or better if you implement the command mode I discussed in
one of my other enhancement requests, one could have a save command like:

:save [optional path to file]

if the path is not specified it falls back to the config file savedir value
which defaults to /tmp with an auto generated filename.
