### ISSUE TITLE
Blank screen at startup / KeyError: 'order'

### ISSUE THREAD

**Issue by tobip** [paul-nameless/tg#180]
I just installed and run tg.
Then I entered my phone number and the security code.
On my phone I got notified that my computer logged in to my telegram account.

But tg only ends in a blank screen, no cursor, nothing.
Is this somewhere a known issue or is there a way to debug tg?

I am running Manjaro ARM64, Sway Desktop, Termite.

**Comment by paul-nameless** [comment]
Hello, there are logs in `~/.local/share/tg/` can you see there something useful?
If there is any errors, send it here (but check that there is no private info).

**Comment by tobip** [comment]
Ah okay, the `error.log` shows this:
```
ERROR [2020-09-18 13:30:22,157] update_handlers.py:32 - wrapper | Error happened in handler: updateChatLastMessage
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/usr/lib/python3.8/site-packages/tg/update_handlers.py", line 192, in update_chat_last_message
    order = update["order"]
KeyError: 'order'
```

**Comment by kunaimaster** [comment]
Hi! Have same issue, confirm!

**Comment by dev0x74** [comment]
Same. In libtdjson they updated API (https://github.com/tdlib/td/commit/06136146511a46bcc26fcb936e3e9ae42130e92c), so there are no `order` field now and new additional notification `updateChatPosition` can come.

I tried to use previous versions of libtdjson, but always got different errors, e.g. for latest release (1.6.0):
```
[ 0][t 4][1604421803.273302078][LogEvent.h:212][#1][!NetStatsManager][&version() < static_cast<int32>(Version::Next)]	Wrong version 28
zsh: segmentation fault  python3.9
```
So I wrote temporary workaround for current version of library (1.6.9):
[0001-Temporary-workaround-for-new-API.patch.zip](https://github.com/paul-nameless/tg/files/5491877/0001-Temporary-workaround-for-new-API.patch.zip)
To apply patch: `> git apply 0001-Temporary-workaround-for-new-API.patch`

**Comment by chux0519** [comment]
@dev0x74 I can confirm it helps, but there are still other errors, it will throw a key error, said no `sender_user_id` in message field. seems the `td` lib remove this field and move the sender's info into a new field named `sender`.

If someone hit the same problem, use following patch may help;
https://gist.github.com/chux0519/1f3765ae1d210a87f266ba034322cd4f

**Comment by ndalliard** [comment]
I applied the two patches and tg now starts succesfully. But on some channels I get:

````python
ERROR [2020-12-04 13:06:07,653] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/controllers.py", line 826, in _render
    self._render_msgs()
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/controllers.py", line 857, in _render_msgs
    self.view.msgs.draw(
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/views.py", line 498, in draw
    msgs_to_draw = self._collect_msgs_to_draw(
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/views.py", line 437, in _collect_msgs_to_draw
    user_id = self.model.users.get_user_label(user_id_item)
  File "/home/nathanael/.local/lib/python3.8/site-packages/tg/models.py", line 821, in get_user_label
    if user["first_name"] and user["last_name"]:
KeyError: 'first_name'
````

Thanks everyone for your awesome help!

**Comment by chux0519** [comment]
@ndalliard yeah, I've encountered the same problem, you can try this patch: https://github.com/chux0519/tg/commit/564696b8c73f1f80ec92a7823bd9d9e7d40992b6
or use the [fork](https://github.com/chux0519/tg)

**Comment by ndalliard** [comment]
@chux0519 Awesome, that works! The only thing I just saw: It shows `<Unknown>` instead of the group name. But that is just a minor bug. Just wanted to mention it here. Thanks for the fork!

**Comment by zonorti** [comment]
The fork works for me, thatnks!
@chux0519 please make a PR to the main repo, this deserves to join the upsteam!
