### ISSUE TITLE
RTL text sometimes overflows beyond the white line onto the chat window

### ISSUE THREAD

**Issue by dkoao** [paul-nameless/tg#184]
I don't know how to reproduce this reliably, but RTL text (Arabic, Persian, etc) sometimes overflows beyond the white barrier and starts spilling text on the chat window, which is very annoying and makes reading old messages a challenge. 

Note that the white barrier doesn't disappear, it gets pushed slightly to the left of the text.

**Comment by paul-nameless** [comment]
Hello, could you please post a screenshot with an example.
Also, it might be a problem because of the emojies.
