### ISSUE TITLE
Some names are missing

### ISSUE THREAD

**Issue by chux0519** [paul-nameless/tg#190]
Not sure how to reproduce this, it seems like some usernames are not shown in group chat messages.

![image](https://user-images.githubusercontent.com/14276970/97824116-08cb3600-1cf6-11eb-8f18-e2fd62a02318.png)

```
❯ pip show tg
Name: tg
Version: 0.6.0
Summary: Terminal client for telegram
Home-page: https://github.com/paul-nameless/tg
Author: Paul Nameless
Author-email: reacsdas@gmail.com
License: UNKNOWN
Location: /home/hexyoungs/miniconda3/lib/python3.8/site-packages
Requires: python-telegram
Required-by:

```

**Comment by paul-nameless** [comment]
Maybe their color is just the same as background?

**Comment by chux0519** [comment]
> Maybe their color is just the same as background?

yeah, that's the reason, thanks for help!

**Comment by paul-nameless** [comment]
You can customize range of colors used to highlight user names.
Check out config description in readme.
