### ISSUE TITLE
Auto download files when openend

### ISSUE THREAD

**Issue by AtomToast** [paul-nameless/tg#191]
I guess somewhat contrary to https://github.com/paul-nameless/tg/issues/163 I actually want to be able to just hit l or enter on a message with an image and if it isn't downloaded yet it should just autodownload it instead of requiring me to press D manually every time beforehand.

**Comment by paul-nameless** [comment]
Will increasing max download size help you?
`MAX_DOWNLOAD_SIZE = "10MB"`

**Comment by AtomToast** [comment]
Even with that it tells me 4KB stickers would need to be downloaded first

**Comment by duffydack** [comment]
Is there any solution or workaround to this yet?  Also, do stickers work or is it just me? 
I have image/*; in mailcap, but it does nothing.  Pressing enter, pressing D, nothing happens.

**Comment by paul-nameless** [comment]
Animated stickers do not working as they have custom format and require converting first
