### ISSUE TITLE
Do not hardcode python-telegram version

### ISSUE THREAD

**Issue by jugendhacker** [paul-nameless/tg#193]
Recently python-telegram released a new version. But tg will not work with this version without patching it, because the version is hard coded here: https://github.com/paul-nameless/tg/blob/master/setup.py#L25

Could you maybe just set a minimum version needed?

**Comment by paul-nameless** [comment]
Yes it's on purpose and I am fine to test it manually (releases are quite seldom). You can create a PR or open issue, I'll try to update and see how is it going)
Thanks for letting me know!

**Comment by jugendhacker** [comment]
Do they change their API that often that you need to hard code and test every version manually?
