### ISSUE TITLE
copy msg text instead of path to file

### ISSUE THREAD

**Issue by ndalliard** [paul-nameless/tg#194]
This is an awesome project, thanks for creating it!

I have the following situation: I get a QR code as an image and the content as text from a bot. Now I would like to get the text into my clipboard and not the path. This is the code (you probably know):

https://github.com/paul-nameless/tg/blob/06f7c5bac3020e1a9912e0dde758f8dd7e7b361c/tg/models.py#L221-L238

Any ideas how to solve this? Or maybe you won't change that behaviour at all.

**Comment by paul-nameless** [comment]
I would prefer to have default behaviour that is right now (copy file's path) but I am okay to add another shortcut to copy the content of the message

**Comment by ndalliard** [comment]
Thanks for getting back. I stopped using `tg` for the moment.
