### ISSUE TITLE
input indicator for Chinese character

### ISSUE THREAD

**Issue by JingMatrix** [paul-nameless/tg#199]
When I compose a short message:
1. If I type English words, there would be a cursor that indicates my input location; it works well and this indicator places at the end of buffer.
2. However, this is not the case when I input Chinese character, if I type 5 Chinese character, the indicator will show at the third position, where I use bold style to indicate the position of cursor:
> 中文**的**鼠标
3. I believe this is related to `curses` python module, and related code is at https://github.com/paul-nameless/tg/blob/master/tg/views.py#L109

**Comment by JingMatrix** [comment]
the same thing happens when I type emoji, which you can try (paste them will work as well):
> 🐟💕🦭

the cursor will be in the second emoji. So this is related to unicode input.

**Comment by jugendhacker** [comment]
Maybe related to #96 ?
