### ISSUE TITLE
Certain colors use the background color only in tmux

### ISSUE THREAD

**Issue by chrisamow** [paul-nameless/tg#210]
Running outside of tmux everything looks fine.
From within tmux some words seem missing on the left column (list of chats)
after trying to figure out what the pattern was I saw that darkmagenta and skyblue text was background colored (close to black)

**Comment by paul-nameless** [comment]
What is the solution? Do you want to have ability to set background colors? Maybe there is a way to change it in tmux?

**Comment by chrisamow** [comment]
I'm not sure yet, I haven't seen that problem in anything else yet, so I don't know how to debug it.
If you're asking how I'd want it to behave - I suppose it shouldn't behave differently from outside of tmux.
I can work around it easily enough for now, but I will at least try to isolate it away from my tmux config.

**Comment by paul-nameless** [comment]
What is the $TERM var?
Try running 
`TERM=xterm-256color tg`

**Comment by chrisamow** [comment]
that didn't work, but putting this in .tmux.conf did do the trick:
```
set -g default-terminal "screen-256color"
```
Thanks for the hint!!

**Comment by paul-nameless** [comment]
🎉 👍 🙏
