### ISSUE TITLE
messages don't show up

### ISSUE THREAD

**Issue by Uanpis** [paul-nameless/tg#229]
Hi, thanks for this amazing telegram client, out of all of the ones I tried it is definitely my favorite so far! :)

I've only got one issue: the messages on the right side of the screen don't show up for some chats, the only exception i could find so far is the Telegram official bot (the one that sends you the verification code)

I'm running the telegram-tg-git package from the AUR on Arch Linux, here's some screenshots:
If I run the docker version tg works as intended, the non-git version works the same as the git version.

here it is working just fine with the Telegram bot:
<img src="https://user-images.githubusercontent.com/22557706/122122760-7fecaf00-ce2d-11eb-9ed8-e9a10cba803d.png" width=300>

here the messages disappear:
<img src="https://user-images.githubusercontent.com/22557706/122123318-246ef100-ce2e-11eb-8325-8644895f9574.png" width=300>
 
If I run with log_level set to debug the program freezes, but here's the log anyway: [all.log](https://github.com/paul-nameless/tg/files/6658942/all.log)

**Comment by jugendhacker** [comment]
Hi, I'm the maintainer of the AUR package. This issue does not happen on my device and telegram account. I also can't find anything obvious in your attached log. But maybe @paul-nameless will find out more.

**Comment by Uanpis** [comment]
Hello, I just reinstalled tg and it works now, but I have no idea what had caused the issue in the first place. I have installed other packages since the issue appeared so it might have been some missing dependencies, but I don't know.

Should I still leave the issue open?

**Comment by jugendhacker** [comment]
I'm not sure. Sounds most likely like an Arch specific issue from my perspective, but let's wait what the maintainers say.

**Comment by paul-nameless** [comment]
Hi, I also don't see anything suspicious in the logs. Maybe error logs were somewhere earlier in the file (there is also special error.log file for this).
Glad that issue resolved auto magically, but without more information or steps to reproduce I'm afraid won't be able to do much.

Closing for now, please, reopen if it will happen again.
