### ISSUE TITLE
AsyncResult error

### ISSUE THREAD

**Issue by allwynfernandes** [paul-nameless/tg#231]
I get this error on running tg from the terminal:
```ImportError: cannot import name 'AsyncResult' from 'telegram.utils' (/home/user/pyenv/lib/python3.8/site-packages/telegram/utils/__init__.py)```

Meta:
OS: Ubuntu 20.04
Py version: 3.8

**Comment by paul-nameless** [comment]
Hello,how do you install it?

**Comment by plum** [comment]
Hello Paul,  I wonder if you could re-open this issue, I get the same problem having installed from aur with yay.

`ImportError: cannot import name 'AsyncResult' from 'telegram.utils' (/home/chuee/.local/lib/python3.9/site-packages/telegram/utils/__init__.py)`

Thanks, John
