### ISSUE TITLE
Long messages are unreadable

### ISSUE THREAD

**Issue by A0405u** [paul-nameless/tg#232]
If the message is bigger then the terminal window, it works unstable. It may show end of the message, or the first message in chat. Is there a possibility to read and scroll such big messages?

**Comment by ihsanturk** [comment]
You can open the message in your editor or any page viewer program using <kbd>!</kbd>

hit <kbd>!</kbd> on the message and type
```
nvim %s
```
or
```
less %s
```

**Comment by paul-nameless** [comment]
Also, you can just press `l` and it will open whole message in the `less` or any other command you specify in config with this variable: `VIEW_TEXT_CMD`
