### ISSUE TITLE
Not using EDITOR variable in A, I

### ISSUE THREAD

**Issue by Wexouv** [paul-nameless/tg#234]
e for editing works fine (opens nvim) but A, I seem to look for vim and ignore EDITOR variable.
`/bin/sh line 1: vim: command not found`
Had to symlink vim to nvim to fix: `sudo ln -s /usr/bin/nvim /usr/bin/vim`

My config:
`EDITOR=os.environ.get("EDITOR", "vi")`
and yes I did: `export EDITOR="/usr/bin/nvim"`

**Comment by paul-nameless** [comment]
Hi, you can use this variable to specify cmd for long msg
LONG_MSG_CMD

It was made as a separate configurable variable, to make it more comfortable, like going straight into insert mode.
