### ISSUE TITLE
How do I reset session?

### ISSUE THREAD

**Issue by poncorobbin** [paul-nameless/tg#247]
Hallo !

I want to change my account using different phone number, i could not found it in the document, i have read the issues also and still could not found any clue.

thank you.

**Comment by paul-nameless** [comment]
Hello, I never did it but I think you can remove this folder
`~/.cache/tg/`
And remove PHONE variable from config file:
`~/.config/tg/conf.py`

**Comment by poncorobbin** [comment]
Thank you!

I recreate this folder manually `~/.cache/tg/` and instead of remove PHONE variable i remove conf.py file itself, start `tg` again and it worked!
