### ISSUE TITLE
Arrow keys in input mode discard message and navigate away

### ISSUE THREAD

**Issue by klemensn** [paul-nameless/tg#248]
Enter a chat, type `i` to compose a message and type away.

Hitting any of the arrow keys will navigate away and discard the message.

I expected left/right to navigate within the message, i.e. move back and
forth for editing, etc. -- instead, all text is lost and I have to start
again.

One work-around is to hit `I` and compose within your editor, but that
goes against the fast type/reply/navigate workflow `tg` naturally provides.

Losing data is bad, so it'd be great to have at least a confirmation about
discarding the unsent message -- better even keep them in a per-chat input
buffer and let users come back to it (just like the mobile app does with
Draft messages).

**Comment by proycon** [comment]
See  #293 , I didn't see there was already an issue for this an implemented a possible fix
