### ISSUE TITLE
tg doesn't load chat

### ISSUE THREAD

**Issue by alen-mat** [paul-nameless/tg#249]
I installed tg through pip
I was able to add my number and enter verification code, after that tg terminated.
Tried opening tg again but it terminates immediately . 
The log file ~/.local/share/tg/error.log is also empty
I am running Arch linux , spectrwm, kitty

**Comment by paul-nameless** [comment]
Did you install requirements? There is a package for Arch available

**Comment by tuxliban** [comment]
I have a similar problem.
I have installed the dependencies and I want to start a session, but the program closes unexpectedly, I get the following log:
```
~
-> $ tg
[ 3][t 4][1639032483.205405950][Td.cpp:4588][#1][!Td][&td_requests]	Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.7.0"
  }
}
[ 3][t 4][1639032483.205590486][Td.cpp:4588][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
  authorization_state = authorizationStateWaitTdlibParameters {
  }
}
Traceback (most recent call last):
  File "/bin/tg", line 33, in <module>
    sys.exit(load_entry_point('tg==0.17.0', 'console_scripts', 'tg')())
  File "/usr/lib/python3.10/site-packages/tg/__main__.py", line 69, in main
    tg.login()
  File "/usr/lib/python3.10/site-packages/telegram/client.py", line 574, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/lib/python3.10/site-packages/telegram/client.py", line 504, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/lib/python3.10/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
```
I have installed version 3.10 of python which is higher than the version indicated in the dependencies```
~
-> $ xbps-query -l | grep python
ii python3-3.10.0_1                      Python programming language (3.10 series)
ii python3-cairo-1.20.1_3             Python3 bindings for the cairo graphics library
ii python3-gobject-3.40.1_2         Python3 bindings for GObject
ii python3-setuptools-58.1.0_1    Easily build and distribute Python3 packages
ii python3-telegram-0.14.0_3       Python library for building Telegram clients

```
