### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by TruncatedDinosour** [paul-nameless/tg#253]
Hello I noticed you have your API key in the config.py file, so I was wondering, I'm modifying tg and adding more features locally
planning on releasing it, so the question is, should I leave it in there or should I create my own?

```py
API_ID = "5xxxx5"
API_HASH = "fdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxca"
```

I censored it just is case heh

**Comment by TruncatedDinosour** [comment]
oops wait

**Comment by paul-nameless** [comment]
Hello, if you are making separate app, please create your own, it's not very complicated, thank you.
