### ISSUE TITLE
UPDATE_APP_TO_LOGIN on execution.

### ISSUE THREAD

**Issue by artur-shaik** [paul-nameless/tg#254]
I have this error after enter phone number:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/tg/__main__.py", line 78, in <module>
    main()
  File "/app/tg/__main__.py", line 69, in main
    tg.login()
  File "/usr/local/lib/python3.9/site-packages/telegram/client.py", line 574, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/local/lib/python3.9/site-packages/telegram/client.py", line 504, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/local/lib/python3.9/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
```

**Comment by pannet1** [comment]
```
  File "/usr/lib/python3.9/site-packages/tg/__main__.py", line 69, in main
    tg.login()
  File "/usr/lib/python3.9/site-packages/telegram/client.py", line 574, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/lib/python3.9/site-packages/telegram/client.py", line 504, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/lib/python3.9/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
```
same error but differant reason

**Comment by TruncatedDinosour** [comment]
this is normal, telegram does not support forks without spensor support (refer to https://core.telegram.org/api/layers#layer-133) so now someone has to add it. I'll try to add it to my fork i guess  👍

**Comment by TruncatedDinosour** [comment]
> ```
>   File "/usr/lib/python3.9/site-packages/tg/__main__.py", line 69, in main
>     tg.login()
>   File "/usr/lib/python3.9/site-packages/telegram/client.py", line 574, in login
>     self.authorization_state = self._wait_authorization_result(result)
>   File "/usr/lib/python3.9/site-packages/telegram/client.py", line 504, in _wait_authorization_result
>     result.wait(raise_exc=True)
>   File "/usr/lib/python3.9/site-packages/telegram/utils.py", line 45, in wait
>     raise RuntimeError(f'Telegram error: {self.error_info}')
> RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
> ```
> 
> same error but differant reason

yeah this is what happens when companies get bigger lol, anyway gotta add sponsored messages support

**Comment by TruncatedDinosour** [comment]
woop nevermind, i guess something different, look at https://github.com/TruncatedDinosour/arigram/issues/2#issuecomment-985790609

**Comment by JingMatrix** [comment]
Just use
`pip install --upgrade python-telegram`

would fix it

**Comment by TruncatedDinosour** [comment]
> Just use `pip install --upgrade python-telegram`
> 
> would fix it

would not, if tg strictly depends on `0.14.0` (`python-telegram==0.14.0`) pip would notice that and refuse to use the newer version

**Comment by JingMatrix** [comment]
It does work for me, I retries it agian.
`pip` just complains, but everything works
```
Requirement already satisfied: python-telegram in /home/jing/.local/lib/python3.9/site-packages (0.14.0)
Collecting python-telegram
  Using cached python_telegram-0.15.0-py3-none-any.whl
Installing collected packages: python-telegram
  Attempting uninstall: python-telegram
    Found existing installation: python-telegram 0.14.0
    Uninstalling python-telegram-0.14.0:
      Successfully uninstalled python-telegram-0.14.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tg 0.17.0 requires python-telegram==0.14.0, but you have python-telegram 0.15.0 which is incompatible.
Successfully installed python-telegram-0.15.0
```
Could you tell me why your `pip` refuse to use the newer version? Maybe you have a system and local installation?

**Comment by TruncatedDinosour** [comment]
> It does work for me, I retries it agian. `pip` just complains, but everything works
> 
> ```
> Requirement already satisfied: python-telegram in /home/jing/.local/lib/python3.9/site-packages (0.14.0)
> Collecting python-telegram
>   Using cached python_telegram-0.15.0-py3-none-any.whl
> Installing collected packages: python-telegram
>   Attempting uninstall: python-telegram
>     Found existing installation: python-telegram 0.14.0
>     Uninstalling python-telegram-0.14.0:
>       Successfully uninstalled python-telegram-0.14.0
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> tg 0.17.0 requires python-telegram==0.14.0, but you have python-telegram 0.15.0 which is incompatible.
> Successfully installed python-telegram-0.15.0
> ```
> 
> Could you tell me why your `pip` refuse to use the newer version? Maybe you have a system and local installation?

Oh, I guess it might work, it seems to be complaining for me either way and not working, but maybe, I have no idea, thanks for the info

**Comment by 0x3n0** [comment]
Traceback (most recent call last):
  File "/sbin/tg", line 33, in <module>
    sys.exit(load_entry_point('tg==0.17.0', 'console_scripts', 'tg')())
  File "/sbin/tg", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for tg

**Comment by paul-nameless** [comment]
Updated pthon-telegram dependency to 0.15.0
