### ISSUE TITLE
Endless update in TG

### ISSUE THREAD

**Issue by d13g0x** [paul-nameless/tg#256]
I installed TG from the AUR. Yesterday and today when I try to execute it, it is updating and never ends.

![2021-12-04-111948_1333x621_scrot](https://user-images.githubusercontent.com/88660859/144716985-4ce0d71c-66a0-4128-ab41-97e1ff12eb84.png)

**Comment by TruncatedDinosour** [comment]
Anything in `~/.local/share/tg/error.log`?

**Comment by d13g0x** [comment]
> Anything in `~/.local/share/tg/error.log`? Might be related to #254

![2021-12-04-180501_752x276_scrot](https://user-images.githubusercontent.com/88660859/144727340-020900b4-b337-4a69-8deb-9925f454793e.png)

**Comment by TruncatedDinosour** [comment]
> > Anything in `~/.local/share/tg/error.log`? Might be related to #254
> 
> ![2021-12-04-180501_752x276_scrot](https://user-images.githubusercontent.com/88660859/144727340-020900b4-b337-4a69-8deb-9925f454793e.png)

Is that it? because these seem fine to me, though TG seems to be broken with 0.14.0 as telegram switched to 64-bit identifiers or something, does the same thing happen with [my fork of tg](https://github.com/TruncatedDinosour/arigram)? it has updated python-telegram, maybe it is related to #254 haha

**Comment by d13g0x** [comment]
> 

Yes, just that, and I think the same as you. I'm going to try your fork.

**Comment by d13g0x** [comment]
> 

Yes, just that, and I think the same as you. I'm going to try your fork.

**Comment by TruncatedDinosour** [comment]
> > 
> 
> Yes, just that, and I think the same as you. I'm going to try your fork. **Update: I dont have problem with your fork**

yep was related to #254 then, wait for paul to update to 0.15.0 of python-telegram and you can go back to using tg :)

**Comment by jugendhacker** [comment]
@d13g0x I just updated the AUR packages for tg to work with latest python-telegram and libtd... now it should work again
