### ISSUE TITLE
tg hanging on startup since update of libtd

### ISSUE THREAD

**Issue by kovidgoyal** [paul-nameless/tg#258]
tg hangs on startup since libtd was updated to 1.7 on Archlinux. I have tried again after deleting ~/.cache/tg. It asks for the code and after entering the code it logs in and then hangs.

And downgrading libtd leads to the following error:
```
[ 0][t 4][1640157472.479521274][LogEvent.h:135][#1][!NetStatsManager][&version() < static_cast<int32>(Version::Next)]	Wrong version 35
```

**Comment by Lafixin** [comment]
Same, I didn't try to downgrade libtd, but yesterday was trying to install tg using yay, which I guess took all last versions of packages, and when I type "tg" in terminal it shows me blank screen and nothing else (like "hanging" or something like that)

**Comment by delightfuldude** [comment]
Same here, terminal stays blank, tg doesn't start anymore.

**Comment by jugendhacker** [comment]
Hi, I'm the maintainer of the related AUR packages and also noticed this error. Seems like libtd broke their API between 1.7.9 and 1.7.10. I would need to investigate this, but currently I don't have that mich time because of Christmas.

**Comment by Galicarnax** [comment]
I observe this issue after update as well on my laptop with Arch/Wayland/Sway. On another machine with Arch/X11/i3wm `tg` works smoothly after update, however.

**Comment by jgoldhammer** [comment]
For me the same on macos! Hanging after installing tdlib from homebrew- crashing without the tdlib from homebrew with "Wrong version 35". Any ideas how I can fix that?

**Comment by kovidgoyal** [comment]
Resolved by latest update to libtd

**Comment by jgoldhammer** [comment]
Hi @kovidgoyal  - I have not seen any update to libtd on github. Can you please point me to the newest release and how to install it?

**Comment by kovidgoyal** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=telegram-tg&id=5c9fdd91d381d666777efdfbc19c3ac3f62b7a7c

**Comment by z8512** [comment]
> Same, I didn't try to downgrade libtd, but yesterday was trying to install tg using yay, which I guess took all last versions of packages, and when I type "tg" in terminal it shows me blank screen and nothing else (like "hanging" or something like that)

Same I build new version tdlib. Everything is blank now
