### ISSUE TITLE
Chats are not rendering on Apple Silicon M1

### ISSUE THREAD

**Issue by FraSharp** [paul-nameless/tg#262]
i basically have the same issue as #260 but on MacOS. I also tried other Telegram CLI projects but none are rendering chats.
I installed this project using brew.

<img width="1458" alt="Screen Shot 2022-02-16 at 22 03 40" src="https://user-images.githubusercontent.com/60934657/154356710-8b4fab1a-c58c-4a50-86a5-b3e348e2fd06.png">

**Comment by z8512** [comment]
What are those other projects?
