### ISSUE TITLE
Yay version broken build

### ISSUE THREAD

**Issue by SlikeDollar** [paul-nameless/tg#287]
Traceback (most recent call last):
  File "/usr/bin/tg", line 5, in <module>
    from tg.__main__ import main
ModuleNotFoundError: No module named 'tg'

**Comment by jugendhacker** [comment]
This error was already reported over at the AUR, you should close this issue here, as it's clearly related to packaging and not tg itself.

**Comment by SlikeDollar** [comment]
Ok
