### ISSUE TITLE
Can't type any messages

### ISSUE THREAD

**Issue by shandsy** [paul-nameless/tg#310]
No clue what might be wrong...

Installed using paru: `paru -S telegram-tg-git`

Went perfectly. Opened, logged in, all good. Tried typing. Neither `i` or `I` does anything. Tried in the chat menu and inside the chats. Tried making a new chat, no difference. I can't figure it out.

I can yank, paste, edit etc. just fine.

**Comment by khaosdoctor** [comment]
This is still happening btw in Arch

**Comment by TroyMitchell911** [comment]
I encountered the same situation in Endeavours (based on arch) and it was very frustrating..
