### ISSUE TITLE
Voice recording buggy

### ISSUE THREAD

**Issue by IvoLeist** [paul-nameless/tg#86]
First of all thanks a lot for this awesome application!

Unfortunately I have some troubles with the voice recording.
Not sure if I ever will use it :D but thought you might be interested.

This was my first bug:
ALSA lib pcm_hw.c:1829:(_snd_pcm_hw_open) Invalid value for card
[alsa @ 0x5626bffac2c0] cannot open audio device default (No such device)
default: Input/output error

Fixed with adding that line to my conf.py
`VOICE_RECORD_CMD = "ffmpeg -f alsa -i hw:0 -c:a libopus -b:a 32k {file_path}"`

But there is still another one:

> Guessed Channel Layout for Input Stream #0.0 : stereo
> Input #0, alsa, from 'hw:0':
>   Duration: N/A, start: 1592929738.453123, bitrate: 1536 kb/s
>     Stream #0:0: Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s
> [NULL @ 0x558585020e00] Unable to find a suitable output format for '/tmp/voice-2020-06-23'
> /tmp/voice-2020-06-23: Invalid argument

**Comment by lightme16** [comment]
Hey @IvoLeist. 
>  VOICE_RECORD_CMD = "ffmpeg -f alsa -i hw:0 -c:a libopus -b:a 32k {file_path}"

this command is also works good to me, we can consider using it as default one for Linux.

regarding you next problem, can you clarify plz how did you install app? Can you plz try to install it from source with:
```pip3 install python-telegram
git clone git@github.com:paul-nameless/tg.git
cd tg
PYTHONPATH=. python3 tg/main.py
```
and reproduce the error?

from you error code:
```
[NULL @ 0x558585020e00] Unable to find a suitable output format for '/tmp/voice-2020-06-23'
/tmp/voice-2020-06-23: Invalid argument
```
 I can see that there problem in quoting output record name, I believe it could be fixed in the https://github.com/paul-nameless/tg/pull/83

**Comment by paul-nameless** [comment]
Let's change the default command for voice recording, though I don't know if it will break for existing users.

**Comment by IvoLeist** [comment]
Could not check it (?)

> ❯ git clone git@github.com:paul-nameless/tg.git
> Cloning into 'tg'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I installed the app via pip install

**Comment by lightme16** [comment]
@IvoLeist plz, clone with  HTTPS instead of SSH:
`git clone https://github.com/paul-nameless/tg.git`

**Comment by IvoLeist** [comment]
Using

```
git clone https://github.com/paul-nameless/tg.git
cd tg
PYTHONPATH=. python3 tg/main.py
```

Everything works as expected :)

You can close that issue

**Comment by lightme16** [comment]
@IvoLeist  Cool! I updated default ffmpeg command for Linux here https://github.com/paul-nameless/tg/pull/95. 
Thanks for your report!
