### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by jugendhacker** [paul-nameless/tg#87]
For those who are to lazy to build this themselves and want to manage it via a package manager on Arch Linux I created a AUR package for it: [telegram-tg-git](https://aur.archlinux.org/packages/telegram-tg-git/)

Maybe you could mention it somewhere as an alternative install method?

**Comment by lightme16** [comment]
Hey, @jugendhacker, thanks for your help! I checked your AUR and it works good for me :+1: 
I happy to mention about it in the README https://github.com/paul-nameless/tg/pull/88

**Comment by paul-nameless** [comment]
Merged 👍
